spring.application.name=project
\# Configurações de Conexão com o MySQL 
spring.datasource.url=jdbc:mysql://localhost:3306/trevo_db?createDatabaseIfNotExist=true&amp&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Rique2030
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver 

# Configurações do JPA / Hibernate 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect